amscapp/urls.py
from amscsait import settings
from . import views
from django.urls import path, include
from django.conf.urls.static import static

urlpatterns = [
    path("list", views.index, name="index"),
    path("admin/", views.admin, name="admin"),
    path("create_proba", views.create_proba, name="create_proba"),
    path("create_patient", views.create_patient, name="create_patient"),
    path("patient/<int:pk>", views.view_patient, name="view_patient"),
    path("patient/<int:pk>/edit", views.edit_patient, name="edit_patient"),
    path("patient/<int:pk>/probs_list", views.probs_list, name="probs_list"),
    path("patient/<int:pk>/probs_list/<int:proba_pk>", views.proba, name="proba"),
    path("patient/<int:pk>/probs_results/<str:slug>", views.probs_results, name="probs_results"),
    path("register", views.register, name="register"),
    #path("login", views.user_login, name="login"),
    path("", views.user_login, name='login'),
    path("exit", views.exit, name="exit"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

amscsait/urls.py
from django.conf.urls.static import static
from amscsait import settings
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("amscapp.urls")),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_DIR)

amscapp/models.py
from datetime import date
from enum import Enum
from django.urls import reverse
from django.core import validators
from django.utils.html import mark_safe
from django.core.validators import MinValueValidator
from django.db.models.signals import pre_save
from django.dispatch import receiver
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from unidecode import unidecode

class QuestionType(Enum):
    POLL = 'poll'
    TEXT = 'text'


class Block(models.Model):
    name = models.CharField("Блок",max_length=100)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Блок"
        verbose_name_plural = "Блоки"

class Modality(models.Model):
    name = models.CharField(max_length=100)
    block = models.ForeignKey(Block, on_delete=models.CASCADE, null=True, blank=True)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Модальность"
        verbose_name_plural = "Модальности"

class Question(models.Model):
    type_ = QuestionType.POLL
    num = models.IntegerField("Номер вопроса", null=True, blank=True)
    question_text = models.CharField("Текст вопроса", max_length=100)
    proba = models.ForeignKey(to="Probs", on_delete=models.CASCADE)
    modality = models.ManyToManyField(Modality)
    avg_value = models.FloatField("Среднее значение", null=True, blank=True)
    min_value = models.FloatField("Минимальное значение", null=True, blank=True)
    max_value = models.FloatField("Максимальное значение", null=True, blank=True)

    def __str__(self):
        return self.question_text

    class Meta:
        verbose_name = "Качественный вопрос"
        verbose_name_plural = "Качественные вопросы"


class Option(models.Model):
    name = models.CharField("Вариант ответа", max_length=100)
    score = models.FloatField("Колличество баллов", default=0)
    question = models.ForeignKey(
        "Question", related_name="options", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Вариант ответа"
        verbose_name_plural = "Варианты ответа"

class NumericQuestion(models.Model):
    question_text = models.CharField("Текст вопроса", max_length=100)
    num = models.IntegerField("Номер вопроса", null=True, blank=True)
    proba = models.ForeignKey(to="Probs", on_delete=models.CASCADE)
    modality = models.ManyToManyField(Modality)
    avg_value = models.FloatField("Среднее значение", null=True, blank=True)
    min_value = models.FloatField("Минимальное значение", null=True, blank=True)
    max_value = models.FloatField("Максимальное значение", null=True, blank=True)
    rev = models.BooleanField(default=False)
    def __str__(self):
        return self.question_text

    class Meta:
        verbose_name = "Числовый вопрос"
        verbose_name_plural = "Числовые вопросы"

class NumericOption(models.Model):
    name = models.CharField("Вариант ответа", max_length=100)
    coefficient = models.FloatField("Коэффициент", default=1)
    question = models.ForeignKey(
        "NumericQuestion", related_name="options", on_delete=models.CASCADE
    )

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = "Числовая опция"
        verbose_name_plural = "Числовые опции"

class Probs(models.Model):
    title = models.CharField(max_length=255)
    modal = models.ForeignKey(Modality, on_delete=models.CASCADE)
    block = models.ForeignKey(Block, on_delete=models.CASCADE, blank=True, null=True)
    slug = models.SlugField(unique=True, blank=True)
    #numer = models.IntegerField("Номер в протоколе",null=True,blank=True)

    def get_results_url(self):
        return reverse('probs_results', kwargs={'pk': self.pk, 'slug': self.slug})

    def save(self, *args, **kwargs):
        # Преобразуем название пробы в английский алфавит и создаем слаг
        if not self.slug:
            english_title = unidecode(self.title)  # Преобразуем название в английский
            self.slug = slugify(english_title)
        super(Probs, self).save(*args, **kwargs)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "Проба"
        verbose_name_plural = "Пробы"


@receiver(pre_save, sender=Probs)
def set_block_from_modal(sender, instance, **kwargs):
    if not instance.block:  # Проверяем, если поле block не заполнено
        instance.block = instance.modal.block

class ProbsImage(models.Model):
    prob = models.ForeignKey(Probs, on_delete=models.CASCADE)
    image = models.ImageField(upload_to='static/image/probs_img/')

    def image_tag(self):
        return mark_safe(f'<img src="{self.image.url}" alt="{self.prob.title}" style="max-width: 100%; height: auto;">')
    image_tag.short_description = 'Image'

    class Meta:
        verbose_name = "Инструкция к пробе"
        verbose_name_plural = "Инструкции к пробам"

class PatientAnswer(models.Model):
    patient = models.ForeignKey(to="Patient", on_delete=models.CASCADE)
    question = models.ForeignKey(to="Question", on_delete=models.CASCADE)
    option = models.ForeignKey(to="Option", on_delete=models.CASCADE)
    proba = models.ForeignKey(to="Probs", on_delete=models.CASCADE)
    modal = models.ForeignKey(to="Modality", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    num = models.IntegerField("Повтор",default=0)
    class Meta:
        verbose_name = "Ответ анкеты"
        verbose_name_plural = "Ответы анкеты"
        db_table = "amscapp_patientanswer"

class PatientNumericAnswer(models.Model):
    patient = models.ForeignKey(to="Patient", on_delete=models.CASCADE)
    question = models.ForeignKey("NumericQuestion", on_delete=models.CASCADE)
    answer = models.IntegerField("Ответ", validators=[MinValueValidator(0)], blank=True)
    proba = models.ForeignKey(to="Probs", on_delete=models.CASCADE)
    modal = models.ForeignKey(to="Modality", on_delete=models.CASCADE)
    created_at = models.DateTimeField(auto_now_add=True)
    num = models.IntegerField("Повтор", default=0)
    class Meta:
        verbose_name = "Ответ на числовый вопрос"
        verbose_name_plural = "Ответы на числовые вопросы"
        db_table = "amscapp_patientnumericanswer"


class Patient(models.Model):
    class GenderChoice(models.TextChoices):
        MAN = "Мужской", "Мужской"
        WOMAN = "Женский", "Женский"

    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField("ФИО", max_length=100)
    date_of_birth = models.DateField("Дата рождения")
    group = models.IntegerField(validators=[validators.MinValueValidator(1), validators.MaxValueValidator(120)],
                                verbose_name='Класс(группа)')
    gender = models.CharField(
        "Пол пациента", max_length=7, choices=GenderChoice.choices, default=GenderChoice.MAN
    )
    #address = models.CharField("Домашний адрес", max_length=100, blank=True)
    parent_name = models.CharField("ФИО родителя/опекуна", max_length=100, blank=True)
    parent_phone_number = models.CharField(
        "Номер контактного телефона родителя/опекуна", max_length=100, blank=True
    )
    parent_email = models.EmailField(
        "Электронная почта родителя/опекуна", max_length=100, blank=True
    )
    plaint = models.TextField(blank=True, verbose_name='Жалобы')
    goal = models.TextField(blank=True, verbose_name='Цель обращения')
    diagnosis = models.TextField(blank=True, verbose_name='Диагноз')
    anamnes = models.TextField(blank=True, verbose_name='Анамнез')
    exam_data = models.TextField(blank=True, verbose_name='Данные наблюдения')

    LEFT_HAND = 'Л'
    RIGHT_HAND = 'П'
    HAND_CHOICES = [(LEFT_HAND, 'Левая'), (RIGHT_HAND, 'Правая'), ]
    hand = models.CharField(max_length=1, choices=HAND_CHOICES, default=RIGHT_HAND, verbose_name='Ведущая рука')

    date_registration = models.DateTimeField("Дата регистрации", auto_now_add=True)

    def __str__(self):
        return self.name

    def calculate_age(self):
        today = date.today()
        return today.year - self.date_of_birth.year - (
                (today.month, today.day) < (self.date_of_birth.month, self.date_of_birth.day))

    class Meta:
        verbose_name = "Пациент"
        verbose_name_plural = "Пациенты"
        db_table = "amscapp_patient"

amscapp/forms.py
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth import get_user_model
from .models import Patient, Probs, Question, Option
from django.contrib.auth.models import User

User = get_user_model()

class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'avg_value', 'min_value', 'max_value']

class OptionForm(forms.ModelForm):
    class Meta:
        model = Option
        fields = ['name', 'score']

class ProbeForm(forms.ModelForm):
    class Meta:
        model = Probs
        fields = ['title', 'modal']
        labels = {
            'title': 'Название',
            'modal': 'Модальность',
        }


class UserLoginForm(AuthenticationForm):
    username = forms.CharField(
        label="Имя пользователя",
        widget=forms.TextInput(attrs={"class": "form-control"}),
    )
    password = forms.CharField(
        label="Пароль", widget=forms.PasswordInput(attrs={"class": "form-control"})

    )


class UserRegisterForm(UserCreationForm):
    error_messages = {}

    email = forms.EmailField(
        label="Электронная почта",
        widget=forms.EmailInput(attrs={"class": "form-control"}),
        error_messages={}
    )
    first_name = forms.CharField(
        label="Имя",
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control"}),
        error_messages={}
    )
    last_name = forms.CharField(
        label="Фамилия",
        max_length=30,
        required=True,
        widget=forms.TextInput(attrs={"class": "form-control"}),
        error_messages={}
    )
    password1 = forms.CharField(
        label="Пароль",
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
        error_messages={}
    )
    password2 = forms.CharField(
        label="Подтверждение пароля",
        widget=forms.PasswordInput(attrs={"class": "form-control"}),
        error_messages={}
    )
    username = forms.CharField(
        label="Имя",
        widget=forms.TextInput(attrs={"class": "form-control"}),
        error_messages={}
    )

    class Meta:
        model = User
        fields = ["username", "email", "first_name", "last_name", "password1", "password2"]


class PatientForm(forms.ModelForm):
    class Meta:
        model = Patient
        fields = ["name", "date_of_birth", "group", "gender", "parent_name", "parent_phone_number", "parent_email", "plaint", "goal", "diagnosis", "anamnes", 'exam_data', "hand"]
        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-input'}),
            'plaint': forms.Textarea(attrs={'cols': 60, 'rows': 8}),
            'goal': forms.Textarea(attrs={'cols': 60, 'rows': 5}),
            'diagnosis': forms.Textarea(attrs={'cols': 60, 'rows': 6}),
            'anamnes': forms.Textarea(attrs={'cols': 60, 'rows': 8}),
            'exam_data': forms.Textarea(attrs={'cols': 60, 'rows': 8}),
            "date_of_birth": forms.DateInput(attrs={"class": "datepicker"}),
        }

amscapp/templates/amscapp/answer_form.html
{% extends 'amscapp/base.html' %}

{% block title %}Анкетирование{% endblock %}

{% block body %}
<div class="container">
  <div class="add">
    <h1>{{ title }}</h1>

    <div class="tabs">
      <input type="radio" name="inset" value="" id="tab_1" checked>
      <label for="tab_1">Жалобы</label>

      <input type="radio" name="inset" value="" id="tab_2">
      <label for="tab_2">У родственников</label>

      <input type="radio" name="inset" value="" id="tab_3">
      <label for="tab_3">Перенесенные заболевания/Сопутствующие заболевания/Соматические заболевания</label>

      <input type="radio" name="inset" value="" id="tab_4">
      <label for="tab_4">Патология развития соединительной ткани</label>

      <input type="radio" name="inset" value="" id="tab_5">
      <label for="tab_5">Основная форма</label>

      <input type="radio" name="inset" value="" id="tab_6">
      <label for="tab_6">Аллергологический анамнез/Гинекологический анамнез</label>

      <input type="radio" name="inset" value="" id="tab_7">
      <label for="tab_7">Клинический анализ крови</label>

      <input type="radio" name="inset" value="" id="tab_8">
      <label for="tab_8">Коагулограмма</label>

      <input type="radio" name="inset" value="" id="tab_9">
      <label for="tab_9">Биохимия крови</label>

      <input type="radio" name="inset" value="" id="tab_10">
      <label for="tab_10">Исследование полиморфных вариантов генов системы гемостаза</label>

      <input type="radio" name="inset" value="" id="tab_11">
      <label for="tab_11">Полиморфные варианты генов фолатного метаболизма</label>

      <div id="txt_1">
        <form method="post">
          {{ form.as_p|slice:":10" }}
        </form>
      </div>

      <div id="txt_2">
        <form method="post">
            {{ form|slice:":10" }}
        </form>
      </div>

      <div id="txt_3">
        <form method="post">
          {{ form.as_table|slice:":10" }}
        </form>
      </div>

      <div id="txt_4">
          <div class="add">
              <form method="post">
                {% for item in questions|slice:"1:5" %}
                  {{ item }}
                {% endfor %}
                  <input class="btn btn-primary btn-block" type="submit" value="{{ submit_text|default:'submit' }}">
              </form>
          </div>
      </div>
  </div>

  <style type="text/css">
  .tabs { width: 100%; padding: 0px; margin: 0 auto; }
  .tabs>input { display: none; }
  .tabs>div {
      display: none;
      padding: 12px;
      border: 1px solid #C0C0C0;
      background: #FFFFFF;
  }
  .tabs>label {
      display: inline-block;
      padding: 7px;
      margin: 0 -5px -1px 0;
      text-align: center;
      color: #000000;
      border: 1px solid #000000;
      background: #FFFFFF;
      cursor: pointer;
  }
  .tabs>input:checked + label {
      color: #000000;
      border: 1px solid #C0C0C0;
      border-bottom: 1px solid #FFFFFF;
      background: #00BCAF;
  }
  #tab_1:checked ~ #txt_1,
  #tab_2:checked ~ #txt_2,
  #tab_3:checked ~ #txt_3,
  #tab_4:checked ~ #txt_4 { display: block; }
  </style>
  </div>
</div>
{% endblock %}

amscapp/templates/amscapp/base.html
{% load static %}
<!doctype html>
<html lang="ru">
<head>
  <meta charset="UTF-8">
  <meta name="viewport"
        content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/css/bootstrap.min.css" integrity="sha384-0evHe/X+R7YkIZDRvuzKMRqM+OrBnVFBL6DOitfPri4tjfHxaWutUpFmBp4vmVor" crossorigin="anonymous">
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.2/css/all.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  {% block extrahead %}{% endblock %}
  <title>{{title}}</title>
</head>

<body>
  <nav class="navbar navbar-expand-xl">
    <div class="container">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent"
        aria-controls="navbarContent" aria-expanded="false">
        <a class="logo">
        <img src="{% static 'image/logo.png' %}" alt="Logo" width="50" height="50">
        </a>
    </button>

    <div class="collapse navbar-collapse" id="navbarContent">
      <ul class="navbar-nav ms-auto mb-lg-0">
        {% if request.user.is_authenticated %}
          <li class="nav-item">
            <a href="{% url 'index' %}" class="nav-link">
            <i class="fas fa-search"></i> Главная
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'create_patient' %}" class="nav-link">
            <i class="fas fa-address-card"></i> Добавить пациента
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'create_proba' %}" class="nav-link">
            <i class="fas fa-plus"></i> Создать пробу
            </a>
          </li>
        </ul>

        <ul class="navbar-nav justify-content-end">
          <li class="nav-item">
            <a href="{% url 'admin' %}" class="nav-link">
              <i class="fas fa-address-book"></i>{{ user.username }}
            </a>
          </li>
          <li class="nav-item">
            <a href="{% url 'exit' %}" class="nav-link">
            <i class="fas fa-sign-out-alt"></i> Выход
            </a>
          </li>
        </ul>
        {% else %}
          <li class="nav-item">
            <a href="{% url 'register' %}" class="nav-link">
            <i class="fas fa-user-plus"></i> Регистрация
            </a>
          </li>

          <li class="nav-item">
            <a href="{% url 'login' %}" class="nav-link">
            <i class="fas fa-sign-in-alt"></i> Авторизация
            </a>
          </li>
        {% endif %}
    </div>
    </div>
  </nav>

{% if messages %}
  {% for message in messages %}
    {% if message.tags == 'error' %}
      <div class="alert alert-danger" role="alert">
        {{ message }}
      </div>
    {% else %}
      <div class="alert alert-{{ message.tags }}" role="alert">
        {{ message }}
      </div>
    {% endif %}
  {% endfor %}
{% endif %}

<main>
  {% block body %}
  {% endblock %}
</main>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-pprn3073KE6tl6bjs2QrFaJGz5/SUsLqktiwsUTF55Jfv3qYSDhgCecCxMW52nD2" crossorigin="anonymous"></script>
</body>
</html>

amscapp/templates/amscapp/create_proba.html
{% extends 'amscapp/base.html' %}
{% load static %}

{% block body %}
<title>Создание пробы</title>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script>
    $(document).ready(function() {
        $('#add-question-btn').click(function() {
            var formsetContainer = $('#formset-container');
            var newForm = formsetContainer.find('.question-form:first').clone();
            newForm.find('input').val('');
            formsetContainer.append(newForm);
        });

        $('#save-forms-btn').click(function() {
            $('form').submit();
        });
    });
</script>

<div class="container">
    <h1>Создание пробы</h1>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button id="add-question-btn" type="button">Добавить вопрос</button>
        <div id="formset-container">
            {% for form in formset %}
                <div class="question-form">
                    {{ form.as_p }}
                </div>
            {% endfor %}
        </div>
        <button id="save-forms-btn" type="submit">Сохранить</button>
    </form>
</div>
{% endblock %}

amscapp/templates/amscapp/index.html
{% extends 'amscapp/base.html' %}

{% block title %}Главная{% endblock %}
{% block body %}
  <div class="container">
  <form class="form-inline my-2 my-lg-0" action="{% url 'index' %}" method="get">
    <div class="input-group mb-3">
      <input type="text" class="form-control" placeholder="Поиск" name="q">
      <button class="btn btn-outline-secondary" type="submit">   Поиск</button>
    </div>
  </form>
    <div class="row">
      <div class="col-md-12">
      <br>
        <table class="table">
          <th>
            Пациент
          </th>
          <th>
            Дата регистрации
          </th>
          {% for patient in patients %}
            <tr>
              <td>
                <a class="btn btn-default" href="{% url 'view_patient' pk=patient.pk %}">{{ patient.name }}</a>
              </td>
              <td>
                {{ patient.date_registration }}
              </td>
            </tr>
          {% endfor %}
        </table>
      </div>
    </div>
  </div>
{% endblock %}

amscapp/templates/amscapp/post_form.html
{% extends 'amscapp/base.html' %}

{% block extrahead %}{{ form.media }}{% endblock %}

{% block body %}
<div class="container">
  <div class="row">
    <h1>{{ title }}</h1>
    <table class="table">
      <form method="post" enctype="multipart/form-data">
        {% csrf_token %}
          {{ form.as_p }}
        <input class="btn btn-primary btn-block" type="submit" value="{{ submit_text|default:'submit' }}">
      </form>
    </table>
  </div>
</div>
{% endblock %}

amscapp/templates/amscapp/proba_detail.html
{% extends 'amscapp/base.html' %}

{% block body %}
{% if request.user.is_authenticated %}
<style>
    .question {
        display: block;
    }

    .option {
        display: block;
        margin-left: 10px;
    }
</style>
    <h1 class="text-center">Вопросы для пробы "{{ prob.title }}"</h1>
    <div class="mt-5">
       <div class="text-center" >
        {% if proba_image %}
            {{ proba_image.image_tag }}
        {% endif %}
    </div>
    </div>
    <div class="container" class="mt-6">
        <div class="row justify-content-center">
            <div class="col-md-8">
                <form method="POST" action="">
                    {% csrf_token %}
                    {% for question in questions %}
                        <div class="mb-4">
                            <h3>{{ question.question_text }}</h3>
                            {% for option in question.options.all %}
                                <label class="option">
                                    <input type="radio" name="question_{{ question.id }}" value="{{ option.id }}" required>
                                    {{ option.name }}
                                </label>
                            {% endfor %}
                        </div>
                    {% endfor %}

                    {% for numeric_question in numeric_questions %}
                        <div class="mb-4">
                            <h3>{{ numeric_question.question_text }}</h3>
                            {% for option in numeric_question.options.all %}
                                {{ option.name }}: <input type="number" name="numeric_question_{{ numeric_question.id }}_{{ option.id }}" step="any" required><br>
                            {% endfor %}
                        </div>
                    {% endfor %}
                    <button type="submit" class="btn btn-primary">Отправить ответы</button>
                </form>
            </div>
        </div>
    </div>
{% endif %}
{% endblock %}

amscapp/templates/amscapp/view_patient.html
{% extends 'amscapp/base.html' %}
{% load static %}
{% block body %}

{% if request.user.is_authenticated %}

<div class="container">

    <div>
        <table class="table">
            <tr>
                <th>Пациент</th>
                <th>Дата рождения</th>
                <th>Дата регистрации</th>
            </tr>
            <tr>
                <td>{{ patient }}</td>
                <td> {{ patient.date_of_birth }} <br> Возраст: {{ patient.calculate_age }} </br></td>
                <td>{{ patient.date_registration }}</td>
            </tr>
        </table>
    </div>

    <div class="row">
        <button class="btn btn-default" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample"
                aria-expanded="false" aria-controls="collapseExample">
            Полная информация о пациенте
        </button>
        <div class="collapse" id="collapseExample">
            <div class="card card-body">
                <div>
                    <h1>{{ patient.name }}</h1>
                    <p>Возраст: {{ patient.calculate_age }}</p>
                    <p>Группа: {{ patient.group }}</p>
                    <p>Ведущая рука: {{ patient.get_hand_display }}</p>
                    <p>Жалобы: {{ patient.plaint }}</p>
                    <p>Цель обращения: {{ patient.goal }}</p>
                    <p>Диагноз: {{ patient.diagnosis }}</p>
                    <p>Анамнестические данные: {{ patient.anamnes }}</p>
                    <p>Данные наблюдения за пациентом в ходе обследования: {{ patient.exam_data }}</p>
                    <div class="collapse" id="collapseExample">
                        <div class="card card-body">
                            <div>
                                <h1>Нейропсихологическое заключение</h1>
                                <p  style="text-decoration: underline;">
                                    <span style="margin-right: 60%;">ФИО: {{ patient.name }}</span>
                                    <span>Дата обследования: - </span>
                                </p>
                                <p  style="text-decoration: underline;">
                                    <span style="margin-right: 70%;">Возраст: {{ patient.calculate_age }}</span>
                                    <span>Группа: {{ patient.group }} </span>
                                </p>

                                <p style="display: inline-block;">
                                    <span style="display: inline-block;font-weight: bold;">Цель обращения:</span>
                                    <span>{{ patient.goal }}</span>
                                    <span>{{ patient.plaint }}</span>
                                    <span>{{ patient.diagnosis }}</span>
                                </p>
                                <p style="display: inline-block;">
                                    <span style="display: inline-block;font-weight: bold;">Анамнестические данные:</span>
                                    <span>{{ patient.anamnes }}</span>
                                </p>
                                <p style="display: inline-block;">
                                    <span style="display: inline-block;font-weight: bold;">Данные наблюдения за пациентом в ходе обследования:</span>
                                    <span>{{ patient.exam_data }}</span>
                                </p>

                                <p style="text-align: center;">Нейропсихологический профиль</p>

                                <img src="{{ chart_image_path }}?timestamp={{ timestamp }}" alt="График" class="centered-image">

                                {% for part_zacl, modality in zacl %}
                                    <p>
                                        <span style="display: inline-block;font-weight: bold;">{{ modality }}</span>
                                        <span>{{ part_zacl }}</span>
                                    </p>
                                {% endfor %}


                            </div>
                        </div>
                    </div>

                </div>
            </div>
        </div>
        <a class="btn btn-warn" href="{% url 'edit_patient' pk=patient.pk %}">Редактировать информацию</a>
        <a class="btn btn-primary btn-block" href="{% url 'probs_list' pk=pk %}">Добавить пробу</a>
    </div>
    <h1>{{ results.total_questions }}</h1>
    {% for modality, html_table in html_tables.items %}
    <div class="row">
        <h2>Параметры оценки функции: {{ modality.name }}</h2>
        {{ html_table|safe }}
    </div>
    {% endfor %}

    <style>
        .resizable-image {
            max-width: 100%;
            max-height: 100%;
            width: 100%;
            height: 40%;
        }


        .centered-image {
            display: block; /* Чтобы можно было использовать margin: auto; */
            margin: auto; /* Центрирует изображение по горизонтали */
            max-width: 100%;
            max-height: 100%;
        }

    </style>
    <div>
        <img src="{%static 'image/graph.png' %}?timestamp={{ timestamp }}" alt="График" class="resizable-image">
        <a class="btn btn-primary btn-block" href="?update-chart">Обновить график</a>
        <a class="btn btn-default" href="?clear-chart">Очистить график</a>
    </div>
</div>
<div class="mt-5"></div>
{% endif %}
{% endblock %}